# Generated by Django 5.1 on 2025-03-20 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraissue',
            name='commits',
            field=models.JSONField(blank=True, max_length=50, null=True),
        ),
    ]
