# Generated by Django 5.1.8 on 2025-08-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_jiraissue_activity_log_jiraissue_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiraissue',
            name='activity_log',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='checklist',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='commits',
        ),
        migrations.RemoveField(
            model_name='jiraissue',
            name='history',
        ),
    ]
